import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ExperienceProvider from "@/components/ExperienceProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                let state = localStorage.getItem("experience-storage");
                if (state) {
                  let parsed = JSON.parse(state);
                  let exp = parsed?.state?.activeExperience;
                  if (exp) {
                    document.documentElement.setAttribute("data-experience", exp);
                  }
                }
              } catch (e) {}
            `,
          }}
        />
        <ExperienceProvider>{children}</ExperienceProvider>
      </body>
    </html>
  );
}
